// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH9q_Ooq6eOXXAWa2OpLLdw1CPNbBlWyA',
    appId: '1:380130115656:web:0f800f4dfff1b0ca00187d',
    messagingSenderId: '380130115656',
    projectId: 'chatboards-app',
    authDomain: 'chatboards-app.firebaseapp.com',
    storageBucket: 'chatboards-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMt1kg0555pniY1gS5I5mbX5UJUBhSRhM',
    appId: '1:380130115656:android:f5cfac62f19fbd8700187d',
    messagingSenderId: '380130115656',
    projectId: 'chatboards-app',
    storageBucket: 'chatboards-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9CmXS1Zzzs0pJY6x3WUhivP5lTA0nwXo',
    appId: '1:380130115656:ios:cc71582479c8a06000187d',
    messagingSenderId: '380130115656',
    projectId: 'chatboards-app',
    storageBucket: 'chatboards-app.firebasestorage.app',
    iosBundleId: 'com.example.messageBoardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9CmXS1Zzzs0pJY6x3WUhivP5lTA0nwXo',
    appId: '1:380130115656:ios:cc71582479c8a06000187d',
    messagingSenderId: '380130115656',
    projectId: 'chatboards-app',
    storageBucket: 'chatboards-app.firebasestorage.app',
    iosBundleId: 'com.example.messageBoardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCH9q_Ooq6eOXXAWa2OpLLdw1CPNbBlWyA',
    appId: '1:380130115656:web:a4eac61c9ea06bf700187d',
    messagingSenderId: '380130115656',
    projectId: 'chatboards-app',
    authDomain: 'chatboards-app.firebaseapp.com',
    storageBucket: 'chatboards-app.firebasestorage.app',
  );
}
